### ISSUE TITLE
Latest sample app does not decode webp Data properly.

### ISSUE THREAD

**Issue by lunayo** [ainame/Swift-WebP#25] opened 2019-09-05 11:04 UTC
I have run the latest sample app and when using encode() function it seems that it is able to encode since it returns result with length > 0. But when tries to decode back the webP data using the decoder function, the image shows gibberish preview on XCode.

The 2 test cases on the webp framework only test if the result is not nil but does not test the content is correct.

**Comment by ainame** [comment] 2019-09-16 23:13
@lunayo Hi. Thank you for reporting this. 
I couldn't replicate your problem with my environment. Can you elaborate on this issue more?

e.g. Steps to replicate this issue or your environment; versions of macOS, Xcode, or Swift

**Comment by ainame** [comment] 2019-09-17 00:07
Thanks to this report, I noticed that I implemented decoding logic wrongly. It can work but it can be misused easily. I'll fix that. 

Currently, you have to specify options like below to get images having the proper size. 

```swift
let decoder = WebPDecoder()
var options = WebPDecoderOptions()
options.useScaling = true
options.scaledWidth = Int(image.size.width)
options.scaledHeight = Int(image.size.height)
let decodedImage = try decoder.decode(data, options: options)
```

The decoder should output images with the same size as the given image when you don't specify width and height or set false to `useScaling`, I guess.

```swift
let decoder = WebPDecoder()
var options = WebPDecoderOptions()
let decodedImage = try decoder.decode(data, options: options)
```

So the decoder and options will work with the above ^.

**Comment by lunayo** [comment] 2019-09-17 05:05
I am using XCode Version 10.3 (10G8), macOS Mojave 10.14.6 (18G95), Swift version 5, tried running on iPad Pro, iPhone X, XS.

Step to reproduce:
1. Running the iOS Example Sample app from the project.
2. The app shows the original image on the top with a button for decoding.
3. Press the button to decode the image.
4. Crash on showing the image.
4. The correct behaviour should show the webp decoded image below.

I believe the issue is due to the deallocation of data when data was formed in decode(), WebPDecoder.swift
```
 return Data(bytesNoCopy: config.output.u.RGBA.rgba,
                    count: config.output.u.RGBA.size,
                    deallocator: .free)
```
if the deallocator is set to .none, the crash issue will be gone
```
 return Data(bytesNoCopy: config.output.u.RGBA.rgba,
                    count: config.output.u.RGBA.size,
                    deallocator: .none)
```

I will try to see if I can fix this.

**Comment by lunayo** [comment] 2019-09-17 07:11
would it be possible to change it to this instead?
```
let data = Data(bytes: config.output.u.RGBA.rgba,
                    count: config.output.u.RGBA.size)
WebPFreeDecBuffer(&config.output)
return data
```

**Comment by ainame** [comment] 2019-09-17 11:01
Ah, I see it's on the physical device. Let me have a look at it on my device first? I tried it only on Simulator last night.

I remember that I intentionally have used `Data(bytesNoCopy:...)` to avoid unnecessary memory copy's overhead. (Because `Data(bytes:...)` copies the decoded binary data by default.) And I guess I would have confirmed that it was working on my iPhone hopefully... (if I recall it correctly🙈 )

**Comment by ainame** [comment] 2019-09-17 23:44
I replicated the issue. I also tried the suggested one but didn't work out neither.

```swift
-        return Data(bytesNoCopy: config.output.u.RGBA.rgba,
-                    count: config.output.u.RGBA.size,
-                    deallocator: .free)
+        defer {
+            var rawValue = config.rawValue
+            WebPFreeDecBuffer(&rawValue.output)
+        }
+        return Data(bytes: config.output.u.RGBA.rgba,
+                    count: config.output.u.RGBA.size)
```

The thing is that I want WebPDecoder.swift to be isolated from UIKit/AppKit stuff so that the common pattern to populating `config.output.u.RGBA.rgba` into CGDataProvider wouldn't fit this case. And also `config` is a struct value so the decoded data would be released when it's out of scope. I'll have a think.

**Closed as completed** 2019-09-23 00:26 UTC

**Comment by ainame** [comment] 2019-09-23 00:31
@lunayo Hi. I fixed the issue. It was not the problem of `WebPDecoder` itself. This went wrong with the use of `CGDataProvider`. 

When this initialiser is used, it seems that `CGDataProvider`  tries to read the `decodedData` asynchronously when a `CGImage` actually is displayed. So decodedData (which specify the deallocator) is highly likely to be released as per how Swift handles value semantics.

https://github.com/ainame/Swift-WebP/blob/8da58773fc69b3aece2823e69e495c35bcd22c87/Sources/WebP/WebPDecoder+Platform.swift#L22-L25

But this behaviour seems to be resolved easily by this simpler initialiser😂 

https://github.com/ainame/Swift-WebP/blob/c635469e974aad7ecafddf694abe7748ec4f6d1a/Sources/WebP/WebPDecoder%2BPlatform.swift#L15-L16
